"""
tank_game_logic.py  –  Pure game-logic layer for the ROS2 Tank Visualizer.

All movement, physics, projectile simulation, collision detection, BOT,
damage/win-loss, wall building, and spark effects live here.

This module has NO ROS2 dependencies – it works with plain Python data
structures so the logic can be tested and reused independently of ROS2.
"""

import math
import random


# ──────────────────────────────────────────────────────────────────────
# Quaternion / rotation utilities
# ──────────────────────────────────────────────────────────────────────

class Quat:
    """Lightweight quaternion container (replaces geometry_msgs.Quaternion
    inside the logic layer so we stay ROS-free)."""
    __slots__ = ('x', 'y', 'z', 'w')

    def __init__(self, x=0.0, y=0.0, z=0.0, w=1.0):
        self.x = x
        self.y = y
        self.z = z
        self.w = w


def euler_to_quat(yaw, pitch, roll):
    """Convert Euler angles to a Quat (same maths as the original
    euler_to_quaternion, but returns a Quat instead of a ROS msg)."""
    qx = (math.sin(roll / 2) * math.cos(pitch / 2) * math.cos(yaw / 2)
          - math.cos(roll / 2) * math.sin(pitch / 2) * math.sin(yaw / 2))
    qy = (math.cos(roll / 2) * math.sin(pitch / 2) * math.cos(yaw / 2)
          + math.sin(roll / 2) * math.cos(pitch / 2) * math.sin(yaw / 2))
    qz = (math.cos(roll / 2) * math.cos(pitch / 2) * math.sin(yaw / 2)
          - math.sin(roll / 2) * math.cos(pitch / 2) * math.cos(yaw / 2))
    qw = (math.cos(roll / 2) * math.cos(pitch / 2) * math.cos(yaw / 2)
          + math.sin(roll / 2) * math.sin(pitch / 2) * math.sin(yaw / 2))
    return Quat(x=qx, y=qy, z=qz, w=qw)


def compose_quat(q_parent, q_child):
    """Multiply two Quats: result = q_parent * q_child."""
    x1, y1, z1, w1 = q_parent.x, q_parent.y, q_parent.z, q_parent.w
    x2, y2, z2, w2 = q_child.x, q_child.y, q_child.z, q_child.w
    return Quat(
        x=w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
        y=w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
        z=w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
        w=w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
    )


def rotate_vec_by_quat(x, y, z, q):
    """Rotate a local-frame vector (x, y, z) by quaternion q, return world-frame (x, y, z)."""
    qx, qy, qz, qw = q.x, q.y, q.z, q.w
    # v' = v + 2*qw*(q_xyz x v) + 2*(q_xyz x (q_xyz x v))
    ux, uy, uz = qx, qy, qz
    # cross1 = u x v
    c1x = uy * z - uz * y
    c1y = uz * x - ux * z
    c1z = ux * y - uy * x
    # cross2 = u x cross1
    c2x = uy * c1z - uz * c1y
    c2y = uz * c1x - ux * c1z
    c2z = ux * c1y - uy * c1x
    rx = x + 2 * qw * c1x + 2 * c2x
    ry = y + 2 * qw * c1y + 2 * c2y
    rz = z + 2 * qw * c1z + 2 * c2z
    return rx, ry, rz


# ──────────────────────────────────────────────────────────────────────
# Main game-logic class
# ──────────────────────────────────────────────────────────────────────

class TankGameLogic:
    """All game state + per-tick update logic, completely ROS-independent."""

    def __init__(self):
        # --- Tank 1 state (player, keyboard controlled) ---
        # Spawn point moved off-center on the open grid (previously 0,0).
        # Tweak these two values if you want to nudge the exact spot further.
        self.x = -3.0
        self.y =  1.5
        self.theta = 0.0
        self.turret_yaw    = 0.0
        self.cannon_pitch  = 0.0
        self.linear_velocity  = 0.0
        self.angular_velocity = 0.0

        # --- Tank 2 state (autonomous tank) ---
        self.turret_yaw2   = 0.0
        self.cannon_pitch2 = 0.0

        # will be positioned properly after wall segments are built (see below)
        self.x2 = 0.0
        self.y2 = 0.0
        self.theta2 = 0.0

        self.auto_speed         = 0.4   # spped
        self.auto_turn_speed    = 1.0   # rad/s max turn rate
        self.auto_target_x      = 0.0
        self.auto_target_y      = 0.0
        self.auto_waypoints     = []    # filled in after wall segments are built
        self.auto_wp_index      = 0
        self.auto_fire_cooldown = random.uniform(2.0, 3.0)
        self.auto_mg_cooldown   = random.uniform(1.2, 2.0)
        self.startup_grace_period = 5.0

        # --- Health / combat state ---
        self.MAX_HP        = 20.0
        self.hp1            = float(self.MAX_HP)   # player tank
        self.hp2            = float(self.MAX_HP)   # auto tank
        self.CANNON_DAMAGE  = 5.0
        self.MG_DAMAGE      = 5.0
        self.game_over       = False
        self.winner          = None   # 'tank1' or 'tank2'

        # Log messages generated by the logic layer.  The ROS node drains
        # this list each tick and forwards the strings to get_logger().info().
        self.pending_log_messages = []

        # -------------------------------------------------------
        # Projectile + spark state
        # Marker ID ranges (must not overlap tanks):
        #   Tank 1:        0 – 299
        #   Tank 2:      300 – 599
        #   Cannon shells: 600 – 699   (max 100 in flight)
        #   MG bullets:    700 – 799   (max 100 in flight)
        #   Sparks:       800 – 2099   (max 1300 active particles)
        #   Walls:        3000+
        #   Health bars:  5000 – 5019
        #   Game over:    6000
        # -------------------------------------------------------
        self.projectiles      = []        # cannon shells
        self.mg_projectiles   = []        # MG bullets
        self.sparks           = []
        self.next_proj_id     = 600
        self.next_mg_proj_id  = 700
        self.next_spark_id    = 800
        self.prev_proj_ids    = set()
        self.prev_mg_proj_ids = set()
        self.prev_spark_ids   = set()
        self.fire_cooldown    = 0.0       # cannon cooldown
        self.mg_cooldown      = 0.0       # MG cooldown

        # Tank dimensions
        self.body_length   = 1.0
        self.body_width    = 0.6
        self.body_height   = 0.3
        self.wheel_radius  = 0.15
        self.wheel_width   = 0.1
        self.turret_radius = 0.25
        self.turret_height = 0.2
        self.cannon_length = 0.6
        self.cannon_radius = 0.05

        self.mg_body_length   = 0.18
        self.mg_body_width    = 0.08
        self.mg_body_height   = 0.08
        self.mg_barrel_length = 0.28
        self.mg_barrel_radius = 0.018
        self.mg_tilt          = 0.15

        # --- Wall / corridor dimensions ---
        self.wall_thickness  = 0.1
        self.wall_height     = 0.4
        self.corridor_width  = 1.8     # clear space between inner wall faces (tank body_width = 0.6)
        self.segment_length  = 6.0     # length of each straight section
        self.corner_origin   = (1.5, -2.0)  # where the corridor starts, tweak to taste

        self.wall_segments = self._build_wall_segments()
        self.wall_aabbs    = self._compute_wall_aabbs()

        # Bounding circle radius used for tank-vs-wall collision checks.
        # (Half the tank's diagonal — a safe over-approximation of the rectangular body.)
        self.collision_radius = math.hypot(self.body_length / 2.0, self.body_width / 2.0)

        # --- Spawn Tank 2 at the entrance to the corridor ---
        ox, oy = self.corner_origin
        L  = self.segment_length
        hw = self.corridor_width / 2.0
        self.x2 = ox + L
        self.y2 = oy
        self.theta2 = math.pi   # facing left along the corridor

        # Path for Tank 2 to follow: along the corridor, then toward the player.
        self.auto_waypoints = [
            (ox + hw, oy),     # move left along the corridor toward the corner
            (ox, oy),          # corridor entrance
            (0.0, 0.0),        # into the open grid, near center
        ]
        self.auto_wp_index = 0

    # ------------------------------------------------------------------
    # Input setters (called by the ROS node's subscription callbacks)
    # ------------------------------------------------------------------

    def set_turret_yaw(self, value):
        self.turret_yaw = value

    def set_cannon_pitch(self, value):
        self.cannon_pitch = max(-0.785, min(0.785, value))

    def set_velocity(self, linear, angular):
        self.linear_velocity  = linear
        self.angular_velocity = angular

    # ------------------------------------------------------------------
    # FIRE — spawn projectile at cannon tip in world-space direction
    # ------------------------------------------------------------------

    def fire_cannon(self):
        if self.game_over:
            return
        if self.fire_cooldown > 0.0:
            return  # still cooling down

        # Total world-space yaw the cannon is pointing
        total_yaw = self.theta + self.turret_yaw
        pitch     = self.cannon_pitch

        # Turret frame origin in world Z
        #   tank body is at z=0.15 in map (see TF below)
        #   turret frame is body_height/2 above that
        turret_origin_z = 0.15 + self.body_height / 2.0   # = 0.30 m

        # Cannon tip offset from turret origin (in turret-local X and Z)
        cannon_horiz = self.cannon_length * math.cos(pitch)   # forward reach
        cannon_vert  = self.turret_height + self.cannon_length * math.sin(pitch)

        # Rotate horizontal reach by world yaw to get world-space tip
        tip_x = self.x + cannon_horiz * math.cos(total_yaw)
        tip_y = self.y + cannon_horiz * math.sin(total_yaw)
        tip_z = turret_origin_z + cannon_vert

        # Projectile velocity (world frame)
        speed = 8.0   # m/s  — adjust to taste
        vx = speed * math.cos(pitch) * math.cos(total_yaw)
        vy = speed * math.cos(pitch) * math.sin(total_yaw)
        vz = speed * math.sin(pitch)

        # Assign a recycling ID (600-699)
        proj_id          = self.next_proj_id
        self.next_proj_id = 600 if self.next_proj_id >= 699 else self.next_proj_id + 1

        self.projectiles.append({
            'id':       proj_id,
            'type':     'cannon',
            'source':   'tank1',
            'x': tip_x, 'y': tip_y, 'z': tip_z,
            'vx': vx,   'vy': vy,   'vz': vz,
            'lifetime': 4.0,        # auto-expire after 4 s
        })

        # Brief muzzle flash at cannon tip
        self._create_spark(tip_x, tip_y, tip_z, lifetime=0.15, is_muzzle=True)

        self.fire_cooldown = 0.4    # 0.4 s between cannon shots

    # ------------------------------------------------------------------
    # MG FIRE — spawn small bullet from MG barrel tip
    # ------------------------------------------------------------------

    def fire_mg(self):
        if self.game_over:
            return
        if self.mg_cooldown > 0.0:
            return  # still cooling down

        total_yaw = self.theta + self.turret_yaw

        # MG barrel mounts at (mg_mount_x, mg_mount_y) in turret frame,
        # tilted upward by mg_tilt, barrel extends mg_barrel_length forward
        mg_mount_x = 0.05
        mg_mount_y = 0.15
        mg_mount_z = 0.15 + self.body_height / 2.0 + self.turret_height + self.mg_body_height / 2.0

        # Full barrel tip offset in turret-local frame
        barrel_reach_x = self.mg_barrel_length * math.cos(self.mg_tilt)
        barrel_reach_z = self.mg_barrel_length * math.sin(self.mg_tilt)

        # Rotate turret-local XY offset into world frame
        local_x = mg_mount_x + barrel_reach_x
        local_y = mg_mount_y

        tip_x = self.x + local_x * math.cos(total_yaw) - local_y * math.sin(total_yaw)
        tip_y = self.y + local_x * math.sin(total_yaw) + local_y * math.cos(total_yaw)
        tip_z = mg_mount_z + barrel_reach_z

        # MG fires flat along turret yaw; gravity handles the drop
        speed = 14.0   # faster than cannon shell
        vx = speed * math.cos(total_yaw)
        vy = speed * math.sin(total_yaw)
        vz = 0.0

        mg_id              = self.next_mg_proj_id
        self.next_mg_proj_id = 700 if self.next_mg_proj_id >= 799 else self.next_mg_proj_id + 1

        self.mg_projectiles.append({
            'id':       mg_id,
            'source':   'tank1',
            'x': tip_x, 'y': tip_y, 'z': tip_z,
            'vx': vx,   'vy': vy,   'vz': vz,
            'lifetime': 2.0,
        })

        # Tiny muzzle flash
        self._create_spark(tip_x, tip_y, tip_z, lifetime=0.08, is_muzzle=True)

        self.mg_cooldown = 0.1    # 10 rounds/sec

    # ------------------------------------------------------------------
    # Tank 2 — autonomous path following + random firing
    # ------------------------------------------------------------------

    def _update_tank2_auto(self, dt):
        if self.game_over:
            return

        if self.auto_wp_index >= len(self.auto_waypoints):
            # Completed the path; hold position and aim at the player.
            desired_turret = math.atan2(self.y - self.y2, self.x - self.x2) - self.theta2
            desired_turret = (desired_turret + math.pi) % (2 * math.pi) - math.pi
            self.turret_yaw2 += max(-0.1 * dt, min(0.1 * dt, desired_turret))

            self.auto_fire_cooldown -= dt
            if self.auto_fire_cooldown <= 0.0:
                self._tank2_fire_cannon()
                self.auto_fire_cooldown = random.uniform(2.5, 4.0)

            self.auto_mg_cooldown -= dt
            if self.auto_mg_cooldown <= 0.0:
                self._tank2_fire_mg()
                self.auto_mg_cooldown = random.uniform(1.5, 2.5)
            return

        target_x, target_y = self.auto_waypoints[self.auto_wp_index]
        dx = target_x - self.x2
        dy = target_y - self.y2
        dist = math.hypot(dx, dy)

        if dist < 0.25:
            self.auto_wp_index += 1
            return

        desired_yaw = math.atan2(dy, dx)
        yaw_diff = (desired_yaw - self.theta2 + math.pi) % (2 * math.pi) - math.pi
        max_turn = self.auto_turn_speed * dt
        self.theta2 += max(-max_turn, min(max_turn, yaw_diff))

        if abs(yaw_diff) < 0.35:
            candidate_x = self.x2 + self.auto_speed * math.cos(self.theta2) * dt
            candidate_y = self.y2 + self.auto_speed * math.sin(self.theta2) * dt
            if not self._collides_with_walls(candidate_x, candidate_y):
                self.x2 = candidate_x
                self.y2 = candidate_y
            elif not self._collides_with_walls(candidate_x, self.y2):
                self.x2 = candidate_x
            elif not self._collides_with_walls(self.x2, candidate_y):
                self.y2 = candidate_y

        self.turret_yaw2 += random.uniform(-0.1, 0.1) * dt

        self.auto_fire_cooldown -= dt
        if self.auto_fire_cooldown <= 0.0:
            self._tank2_fire_cannon()
            self.auto_fire_cooldown = random.uniform(2.0, 3.5)

        self.auto_mg_cooldown -= dt
        if self.auto_mg_cooldown <= 0.0:
            self._tank2_fire_mg()
            self.auto_mg_cooldown = random.uniform(1.2, 2.5)

    def _tank2_fire_cannon(self):
        total_yaw = self.theta2 + self.turret_yaw2 + random.uniform(-0.6, 0.6)
        pitch = random.uniform(-0.2, 0.2)

        turret_origin_z = 0.15 + self.body_height / 2.0
        cannon_horiz = self.cannon_length * math.cos(pitch)
        cannon_vert  = self.turret_height + self.cannon_length * math.sin(pitch)

        tip_x = self.x2 + cannon_horiz * math.cos(total_yaw)
        tip_y = self.y2 + cannon_horiz * math.sin(total_yaw)
        tip_z = turret_origin_z + cannon_vert

        speed = 8.0
        vx = speed * math.cos(pitch) * math.cos(total_yaw)
        vy = speed * math.cos(pitch) * math.sin(total_yaw)
        vz = speed * math.sin(pitch)

        proj_id = self.next_proj_id
        self.next_proj_id = 600 if self.next_proj_id >= 699 else self.next_proj_id + 1

        self.projectiles.append({
            'id': proj_id, 'type': 'cannon', 'source': 'tank2',
            'x': tip_x, 'y': tip_y, 'z': tip_z,
            'vx': vx, 'vy': vy, 'vz': vz,
            'lifetime': 4.0,
        })
        self._create_spark(tip_x, tip_y, tip_z, lifetime=0.15, is_muzzle=True)

    def _tank2_fire_mg(self):
        total_yaw = self.theta2 + self.turret_yaw2 + random.uniform(-0.8, 0.8)
        mg_mount_z = 0.15 + self.body_height / 2.0 + self.turret_height + self.mg_body_height / 2.0

        tip_x = self.x2 + 0.2 * math.cos(total_yaw)
        tip_y = self.y2 + 0.2 * math.sin(total_yaw)
        tip_z = mg_mount_z

        speed = 14.0
        vx = speed * math.cos(total_yaw)
        vy = speed * math.sin(total_yaw)
        vz = 0.0

        mg_id = self.next_mg_proj_id
        self.next_mg_proj_id = 700 if self.next_mg_proj_id >= 799 else self.next_mg_proj_id + 1

        self.mg_projectiles.append({
            'id': mg_id, 'source': 'tank2',
            'x': tip_x, 'y': tip_y, 'z': tip_z,
            'vx': vx, 'vy': vy, 'vz': vz, 'lifetime': 2.0,
        })
        self._create_spark(tip_x, tip_y, tip_z, lifetime=0.08, is_muzzle=True)

    # ------------------------------------------------------------------
    # Damage / win-loss
    # ------------------------------------------------------------------

    def _apply_damage(self, shooter_source, dmg):
        """shooter_source is who FIRED the shot; damage lands on the other tank."""
        if self.game_over:
            return

        # Give the player a short spawn grace period so Tank 2 cannot
        # immediately end the match before the first movement input.
        if self.startup_grace_period > 0.0 and shooter_source == 'tank2':
            return

        if shooter_source == 'tank1':
            self.hp2 = max(0, self.hp2 - dmg)
            if self.hp2 <= 0:
                self.game_over = True
                self.winner = 'tank1'
                self.pending_log_messages.append('Tank 2 destroyed — YOU WIN!')
        else:
            self.hp1 = max(0, self.hp1 - dmg)
            if self.hp1 <= 0:
                self.game_over = True
                self.winner = 'tank2'
                self.pending_log_messages.append('Tank 1 destroyed — YOU LOSE!')

    # ------------------------------------------------------------------
    # Spark factory
    # ------------------------------------------------------------------

    def _create_spark(self, x, y, z, lifetime=0.5, is_muzzle=False):
        """
        Spawn a burst of spark particles at world position (x, y, z).

        Each particle gets its own random velocity so they fan out like
        real sparks flying off an impact or muzzle flash.

        is_muzzle=True  → compact white-hot flash (fewer, faster, brighter)
        is_muzzle=False → impact burst (more particles, orange/red, drift wider)
        """
        num_particles = 5 if is_muzzle else 14
        base_speed    = 3.0 if is_muzzle else 2.0

        for _ in range(num_particles):
            spark_id           = self.next_spark_id
            self.next_spark_id = 800 if self.next_spark_id >= 2099 else self.next_spark_id + 1

            # Random direction spread (full sphere for impact, forward cone for muzzle)
            if is_muzzle:
                # Tight forward cone ± 60°
                yaw_spread   = random.uniform(-math.pi / 3, math.pi / 3)
                pitch_spread = random.uniform(-math.pi / 4, math.pi / 4)
            else:
                # Full hemisphere upward (sparks bounce off surface)
                yaw_spread   = random.uniform(-math.pi, math.pi)
                pitch_spread = random.uniform(0.0, math.pi / 2)

            speed = base_speed * random.uniform(0.4, 1.0)
            vx = speed * math.cos(pitch_spread) * math.cos(yaw_spread)
            vy = speed * math.cos(pitch_spread) * math.sin(yaw_spread)
            vz = speed * math.sin(pitch_spread) + (0.5 if not is_muzzle else 0.0)

            part_lifetime = lifetime * random.uniform(0.6, 1.0)

            self.sparks.append({
                'id':             spark_id,
                'x': x, 'y': y, 'z': z,
                'vx': vx, 'vy': vy, 'vz': vz,
                'lifetime':       part_lifetime,
                'total_lifetime': part_lifetime,
                'is_muzzle':      is_muzzle,
            })

    # ------------------------------------------------------------------
    # Per-tick updates
    # ------------------------------------------------------------------

    def _update_projectiles(self, dt):
        """Move projectiles, check collisions, spawn sparks + apply damage on hit."""
        still_active = []

        t1cx, t1cy, t1cz = self.x,  self.y,  0.15 + self.body_height / 2.0
        t2cx, t2cy, t2cz = self.x2, self.y2, 0.15 + self.body_height / 2.0
        hit_radius = 0.55                         # generous hitbox

        for p in self.projectiles:
            # Integrate position
            p['x'] += p['vx'] * dt
            p['y'] += p['vy'] * dt
            p['z'] += p['vz'] * dt
            p['lifetime'] -= dt

            # Discard if expired (no spark — it just vanished off-screen)
            if p['lifetime'] <= 0:
                continue

            hit = False

            # --- Ground hit ---
            if p['z'] < 0.1:
                self._create_spark(p['x'], p['y'], 0.1, lifetime=0.5, is_muzzle=False)
                hit = True

            # --- Tank hit (whichever tank did NOT fire this shot) ---
            if not hit:
                source = p.get('source', 'tank1')
                if source == 'tank2':
                    tx, ty, tz = t1cx, t1cy, t1cz
                else:
                    tx, ty, tz = t2cx, t2cy, t2cz

                d = math.sqrt(
                    (p['x'] - tx) ** 2 +
                    (p['y'] - ty) ** 2 +
                    (p['z'] - tz) ** 2
                )
                if d < hit_radius:
                    self._create_spark(p['x'], p['y'], p['z'], lifetime=0.6, is_muzzle=False)
                    self._apply_damage(source, self.CANNON_DAMAGE)
                    hit = True

            if not hit:
                still_active.append(p)

        self.projectiles = still_active

    def _update_mg_projectiles(self, dt):
        """Move MG bullets, check collisions, spawn small sparks + apply damage on hit."""
        GRAVITY = -9.81   # m/s² — real gravity so bullets drop to target height
        still_active = []

        t1cx, t1cy, t1cz = self.x,  self.y,  0.15 + self.body_height / 2.0
        t2cx, t2cy, t2cz = self.x2, self.y2, 0.15 + self.body_height / 2.0
        hit_radius = 0.55

        for p in self.mg_projectiles:
            p['vz'] += GRAVITY * dt   # gravity pulls bullet down each tick
            p['x'] += p['vx'] * dt
            p['y'] += p['vy'] * dt
            p['z'] += p['vz'] * dt
            p['lifetime'] -= dt

            if p['lifetime'] <= 0:
                continue

            hit = False

            # Ground hit — tiny spark
            if p['z'] < 0.1:
                self._create_spark(p['x'], p['y'], 0.1, lifetime=0.2, is_muzzle=False)
                hit = True

            # Tank hit — small spark + damage
            if not hit:
                source = p.get('source', 'tank1')
                if source == 'tank2':
                    tx, ty, tz = t1cx, t1cy, t1cz
                else:
                    tx, ty, tz = t2cx, t2cy, t2cz

                d = math.sqrt(
                    (p['x'] - tx) ** 2 +
                    (p['y'] - ty) ** 2 +
                    (p['z'] - tz) ** 2
                )
                if d < hit_radius:
                    self._create_spark(p['x'], p['y'], p['z'], lifetime=0.25, is_muzzle=False)
                    self._apply_damage(source, self.MG_DAMAGE)
                    hit = True

            if not hit:
                still_active.append(p)

        self.mg_projectiles = still_active

    def _update_sparks(self, dt):
        """Tick down spark lifetimes, move each particle, apply gravity, remove dead ones."""
        GRAVITY = -4.0   # m/s²  — lighter than real so sparks arc nicely
        new_sparks = []
        for s in self.sparks:
            s['lifetime'] -= dt
            if s['lifetime'] <= 0:
                continue
            # Integrate position
            s['x']  += s['vx'] * dt
            s['y']  += s['vy'] * dt
            s['z']  += s['vz'] * dt
            # Gravity drags Z velocity down
            s['vz'] += GRAVITY * dt
            # Stop at ground
            if s['z'] < 0.02:
                s['z']  = 0.02
                s['vz'] = 0.0
            new_sparks.append(s)
        self.sparks = new_sparks

    # ------------------------------------------------------------------
    # Wall / corridor builders
    # ------------------------------------------------------------------

    def _build_wall_segments(self):
        """
        Build a right-angle corridor: straight east, turn right, straight south.
        Returns a list of (x_center, y_center, length, thickness, yaw) for CUBE markers.
        Outer wall corner is squared off, inner wall corner is cut back,
        so the turn is actually driveable.
        """
        ox, oy = self.corner_origin
        L  = self.segment_length
        hw = self.corridor_width / 2.0
        t  = self.wall_thickness

        segs = []

        # --- Outer wall (the wide/outside of the turn) ---
        # Segment 1: runs along x, from ox to ox+L+hw (extended to cover the corner)
        seg1_len = L + hw
        segs.append((ox + seg1_len / 2.0, oy + hw, seg1_len, t, 0.0))

        # Segment 2: runs along y (south), from oy+hw down to oy-L
        seg2_len = L + hw
        segs.append((ox + L + hw, oy + hw - seg2_len / 2.0, seg2_len, t, math.pi / 2.0))

        # --- Inner wall (the tight/inside of the turn) ---
        # Segment 1: cut short so the corner opening isn't blocked
        seg3_len = L - hw
        segs.append((ox + seg3_len / 2.0, oy - hw, seg3_len, t, 0.0))

        # Segment 2: also cut short
        seg4_len = L - hw
        segs.append((ox + L - hw, oy - hw - seg4_len / 2.0, seg4_len, t, math.pi / 2.0))

        return segs

    def _compute_wall_aabbs(self):
        """
        Convert each wall segment into an axis-aligned bounding box
        (xmin, xmax, ymin, ymax). Safe because every wall segment's yaw
        is either 0 (horizontal) or pi/2 (vertical) — no diagonal walls.
        """
        aabbs = []
        for (cx, cy, length, thickness, yaw) in self.wall_segments:
            half_len   = length / 2.0
            half_thick = thickness / 2.0
            if abs(math.sin(yaw)) < 0.5:
                # horizontal segment: long along x, thin along y
                aabbs.append((cx - half_len, cx + half_len, cy - half_thick, cy + half_thick))
            else:
                # vertical segment: thin along x, long along y
                aabbs.append((cx - half_thick, cx + half_thick, cy - half_len, cy + half_len))
        return aabbs

    def _collides_with_walls(self, x, y):
        """
        Circle-vs-AABB test: True if a circle of radius self.collision_radius
        centered at (x, y) overlaps any wall's bounding box.
        """
        r2 = self.collision_radius * self.collision_radius
        for (xmin, xmax, ymin, ymax) in self.wall_aabbs:
            closest_x = max(xmin, min(x, xmax))
            closest_y = max(ymin, min(y, ymax))
            dx = x - closest_x
            dy = y - closest_y
            if dx * dx + dy * dy < r2:
                return True
        return False

    # ------------------------------------------------------------------
    # Main per-tick update  (called from the ROS node's timer callback)
    # ------------------------------------------------------------------

    def update(self, dt):
        """Advance game state by dt seconds."""
        if self.startup_grace_period > 0.0:
            self.startup_grace_period = max(0.0, self.startup_grace_period - dt)

        if not self.game_over:
            # --- Tank 1 movement (with wall collision) ---
            self.theta += self.angular_velocity * dt

            candidate_x = self.x + self.linear_velocity * math.cos(self.theta) * dt
            candidate_y = self.y + self.linear_velocity * math.sin(self.theta) * dt

            if not self._collides_with_walls(candidate_x, candidate_y):
                # No collision — move freely
                self.x = candidate_x
                self.y = candidate_y
            elif not self._collides_with_walls(candidate_x, self.y):
                # Blocked diagonally, but sliding along x alone is clear
                self.x = candidate_x
            elif not self._collides_with_walls(self.x, candidate_y):
                # Sliding along y alone is clear
                self.y = candidate_y
            # else: fully blocked — tank stays put this tick

            # --- Tank 2 autonomous movement + firing ---
            self._update_tank2_auto(dt)

        # --- Fire cooldown tick ---
        self.fire_cooldown = max(0.0, self.fire_cooldown - dt)
        self.mg_cooldown   = max(0.0, self.mg_cooldown   - dt)

        # --- Update projectiles and sparks (let existing shots finish even at game over) ---
        self._update_projectiles(dt)
        self._update_mg_projectiles(dt)
        self._update_sparks(dt)
